### ISSUE TITLE
Nominations Timeline Table

### ISSUE THREAD

**Issue by pwensing** [pwensing/RAS-Governance#27]
Create a summary table for the timeline of the nominations in P&P (see, e.g., Sec. 2.11)

**Comment by JenJenChung** [comment]
Cleaned up the table in Appendix C:
<b id="docs-internal-guid-45f7ca6f-7fff-e726-6ae4-ce1764ac4eb1" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-weight: normal;"><div dir="ltr" align="left" style="margin-left: 0pt;">
Milestone | Recommended date | Latest date | Days to next milestone
-- | -- | -- | --
Petitions to IEEE | 15 May | 23 May | 30
Nominations to Society Administrator | 15 June | 22 June | 7
Nominations and Petition Certification to Nominations Committee<br>Schedule telecom (15 days)<br>Committee Voting (15 days)<br>Materials gathered from candidates (30 days) | 21 June | 29 June | 60
Nomination materials to IEEE | 25 August | 28 August | 60
Election Open | 25 October | 27 October | 42 (6 weeks)
Election Close | 7 December | 8 December | 7
Date of Results | 15 December | 15 December |  

</div></b>
