### ISSUE TITLE
Name Change: Nominations and Appointments Committee

### ISSUE THREAD

**Issue by pwensing** [pwensing/RAS-Governance#5]
Change name from Nominations Committee to Nominations and Appointments Committee.

**Comment by pwensing** [comment]
Faith will check with Seth to feel this one out first.

**Comment by pwensing** [comment]
Coupled with the VP matters -- address this all together.

**Comment by pwensing** [comment]
Reading through more carefully -- even if we make the VP election a confirmation, the Nominations Committee is still only nominating the candidate. They aren't appointing anyone without confirmation. So, I think the name Nominations Committee is still the right one. Given the historical inertia here, I think we should stick with the original name. 

@kmombaur Do you agree?

**Comment by kmombaur** [comment]
I agree

**Comment by pwensing** [comment]
Keeping name as Nominations Committee for now since the update seems uncessary.
